
package com.api.isms.org.csapi.wsdl.parlayx.sms.send.v2_2.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.api.isms.org.csapi.schema.parlayx.common.v2_1.ChargingInformation;
import com.api.isms.org.csapi.schema.parlayx.common.v2_1.NamedParameterList;
import com.api.isms.org.csapi.schema.parlayx.common.v2_1.SimpleReference;
import com.api.isms.org.csapi.schema.parlayx.sms.v2_2.DeliveryInformation;
import com.api.isms.org.csapi.schema.parlayx.sms.v2_2.SmsFormat;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SendSms", targetNamespace = "http://www.csapi.org/wsdl/parlayx/sms/send/v2_2/interface")
@XmlSeeAlso({
    com.api.isms.cn.com.huawei.schema.common.v2_1.ObjectFactory.class,
    com.api.isms.org.csapi.schema.parlayx.common.v2_1.ObjectFactory.class,
    com.api.isms.org.csapi.schema.parlayx.sms.send.v2_2.local.ObjectFactory.class,
    com.api.isms.org.csapi.schema.parlayx.sms.v2_2.ObjectFactory.class
})
public interface SendSms {


    /**
     * 
     * @param encode
     * @param sourceport
     * @param destinationport
     * @param addresses
     * @param senderName
     * @param extensionInfo
     * @param receiptRequest
     * @param dataCoding
     * @param charging
     * @param message
     * @param esmClass
     * @return
     *     returns java.lang.String
     * @throws ServiceException
     * @throws PolicyException
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")
    @RequestWrapper(localName = "sendSms", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local", className = "org.csapi.schema.parlayx.sms.send.v2_2.local.SendSms")
    @ResponseWrapper(localName = "sendSmsResponse", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local", className = "org.csapi.schema.parlayx.sms.send.v2_2.local.SendSmsResponse")
    public String sendSms(
        @WebParam(name = "addresses", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")
        List<String> addresses,
        @WebParam(name = "senderName", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")
        String senderName,
        @WebParam(name = "charging", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")
        ChargingInformation charging,
        @WebParam(name = "message", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")
        String message,
        @WebParam(name = "receiptRequest", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")
        SimpleReference receiptRequest,
        @WebParam(name = "encode", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")
        String encode,
        @WebParam(name = "sourceport", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")
        Integer sourceport,
        @WebParam(name = "destinationport", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")
        Integer destinationport,
        @WebParam(name = "esm_class", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")
        Integer esmClass,
        @WebParam(name = "data_coding", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")
        Integer dataCoding,
        @WebParam(name = "extensionInfo", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")
        NamedParameterList extensionInfo)
        throws PolicyException, ServiceException
    ;

    /**
     * 
     * @param image
     * @param addresses
     * @param senderName
     * @param receiptRequest
     * @param charging
     * @param smsFormat
     * @return
     *     returns java.lang.String
     * @throws ServiceException
     * @throws PolicyException
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")
    @RequestWrapper(localName = "sendSmsLogo", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local", className = "org.csapi.schema.parlayx.sms.send.v2_2.local.SendSmsLogo")
    @ResponseWrapper(localName = "sendSmsLogoResponse", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local", className = "org.csapi.schema.parlayx.sms.send.v2_2.local.SendSmsLogoResponse")
    public String sendSmsLogo(
        @WebParam(name = "addresses", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")
        List<String> addresses,
        @WebParam(name = "senderName", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")
        String senderName,
        @WebParam(name = "charging", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")
        ChargingInformation charging,
        @WebParam(name = "image", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")
        byte[] image,
        @WebParam(name = "smsFormat", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")
        SmsFormat smsFormat,
        @WebParam(name = "receiptRequest", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")
        SimpleReference receiptRequest)
        throws PolicyException, ServiceException
    ;

    /**
     * 
     * @param addresses
     * @param senderName
     * @param receiptRequest
     * @param charging
     * @param ringtone
     * @param smsFormat
     * @return
     *     returns java.lang.String
     * @throws ServiceException
     * @throws PolicyException
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")
    @RequestWrapper(localName = "sendSmsRingtone", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local", className = "org.csapi.schema.parlayx.sms.send.v2_2.local.SendSmsRingtone")
    @ResponseWrapper(localName = "sendSmsRingtoneResponse", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local", className = "org.csapi.schema.parlayx.sms.send.v2_2.local.SendSmsRingtoneResponse")
    public String sendSmsRingtone(
        @WebParam(name = "addresses", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")
        List<String> addresses,
        @WebParam(name = "senderName", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")
        String senderName,
        @WebParam(name = "charging", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")
        ChargingInformation charging,
        @WebParam(name = "ringtone", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")
        String ringtone,
        @WebParam(name = "smsFormat", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")
        SmsFormat smsFormat,
        @WebParam(name = "receiptRequest", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")
        SimpleReference receiptRequest)
        throws PolicyException, ServiceException
    ;

    /**
     * 
     * @param requestIdentifier
     * @return
     *     returns java.util.List<org.csapi.schema.parlayx.sms.v2_2.DeliveryInformation>
     * @throws ServiceException
     * @throws PolicyException
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")
    @RequestWrapper(localName = "getSmsDeliveryStatus", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local", className = "org.csapi.schema.parlayx.sms.send.v2_2.local.GetSmsDeliveryStatus")
    @ResponseWrapper(localName = "getSmsDeliveryStatusResponse", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local", className = "org.csapi.schema.parlayx.sms.send.v2_2.local.GetSmsDeliveryStatusResponse")
    public List<DeliveryInformation> getSmsDeliveryStatus(
        @WebParam(name = "requestIdentifier", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")
        String requestIdentifier)
        throws PolicyException, ServiceException
    ;

}
